---
modality1:
  csv_file: 
  path_to_search: "./example_volumes/monomodal_parcellation"
  filename_contains: T1
  filename_not_contains: 
  spatial_window_size: "(20, 42, 42)"
  interp_order: 3
  pixdim: "(1.0, 1.0, 1.0)"
  axcodes: "(A, R, S)"
label:
  path_to_search: "./example_volumes/monomodal_parcellation"
  filename_contains: Label
  filename_not_contains: 
  spatial_window_size: "(20, 42, 42)"
  interp_order: 0
  pixdim: "(1.0, 1.0, 1.0)"
  axcodes: "(A, R, S)"
SYSTEM:
  cuda_devices: 
  num_threads: 2
  num_gpus: 1
  model_dir: "./models/model_monomodal_toy"
NETWORK:
  name: toynet
  activation_function: prelu
  batch_size: 1
  decay: 0.1
  reg_type: L2
  volume_padding_size: 21
  histogram_ref_file: "./example_volumes/monomodal_parcellation/standardisation_models.txt"
  norm_type: percentile
  cutoff: "(0.01, 0.99)"
  normalisation: false
  whitening: false
  normalise_foreground_only: true
  foreground_type: otsu_plus
  multimod_foreground_type: and
  queue_length: 20
TRAINING:
  sample_per_volume: 32
  rotation_angle: "(-10.0, 10.0)"
  scaling_percentage: "(-10.0, 10.0)"
  random_flipping_axes: 1
  lr: 0.01
  loss_type: Dice
  starting_iter: 0
  save_every_n: 100
  max_iter: 10
  max_checkpoints: 20
INFERENCE:
  border: "(0, 0, 1)"
  save_seg_dir: "./output/toy"
  output_interp_order: 0
  spatial_window_size: "(0, 0, 3)"
EVALUATION:
  evaluations: Dice
SEGMENTATION:
  image: modality1
  label: label
  output_prob: false
  num_classes: 160
  label_normalisation: true
