---
T1:
  csv_file: 
  path_to_search: "./example_volumes/multimodal_BRATS"
  filename_contains: T1
  filename_not_contains: T1c
  spatial_window_size: "(64, 64, 64)"
  interp_order: 3
T2:
  csv_file: 
  path_to_search: "./example_volumes/multimodal_BRATS"
  filename_contains: T2
  filename_not_contains: 
  spatial_window_size: "(64, 64, 64)"
  interp_order: 3
T1c:
  csv_file: 
  path_to_search: "./example_volumes/multimodal_BRATS"
  filename_contains: T1c
  filename_not_contains: 
  spatial_window_size: "(64, 64, 64)"
  interp_order: 3
Flair:
  csv_file: 
  path_to_search: "./example_volumes/multimodal_BRATS"
  filename_contains: Flair
  filename_not_contains: 
  spatial_window_size: "(64, 64, 64)"
  interp_order: 3
label:
  csv_file: 
  path_to_search: "./example_volumes/multimodal_BRATS"
  filename_contains: Label
  filename_not_contains: 
  spatial_window_size: "(64, 64, 64)"
  interp_order: 0
SYSTEM:
  cuda_devices: 
  num_threads: 2
  num_gpus: 1
  model_dir: "./models/model_multimodal_toy"
  queue_length: 20
NETWORK:
  name: toynet
  activation_function: prelu
  batch_size: 1
  decay: 0
  reg_type: L2
  volume_padding_size: 21
  histogram_ref_file: "./example_volumes/multimodal_parcellation/standardisation_models.txt"
  norm_type: percentile
  cutoff: "(0.01, 0.99)"
  normalisation: true
  whitening: true
  normalise_foreground_only: false
  foreground_type: otsu_plus
  multimod_foreground_type: and
TRAINING:
  sample_per_volume: 32
  lr: 0.01
  loss_type: WGDL
  starting_iter: 0
  save_every_n: 100
  max_iter: 10
  max_checkpoints: 20
INFERENCE:
  border: 5
  save_seg_dir: "./output/toy"
  output_interp_order: 0
  spatial_window_size: "(64, 64, 64)"
EVALUATION: {}
SEGMENTATION:
  image: T1,T2,T1c,Flair
  label: label
  weight: T1
  output_prob: false
  num_classes: 5
  label_normalisation: true
