---
T1:
  path_to_search: "./example_volumes/multimodal_BRATS"
  filename_contains: T1
  filename_not_contains: T1c
  spatial_window_size: "(32, 32, 32)"
  interp_order: 3
Flair:
  path_to_search: "./example_volumes/multimodal_BRATS"
  filename_contains: Flair
  filename_not_contains: 
  spatial_window_size: "(32, 32, 32)"
  interp_order: 3
T1c:
  path_to_search: "./example_volumes/multimodal_BRATS"
  filename_contains: T1c
  filename_not_contains: 
  spatial_window_size: "(32, 32, 32)"
  interp_order: 3
T2:
  path_to_search: "./example_volumes/multimodal_BRATS"
  filename_contains: T2
  filename_not_contains: 
  spatial_window_size: "(32, 32, 32)"
  interp_order: 3
label:
  path_to_search: "./example_volumes/multimodal_BRATS"
  filename_contains: Label
  filename_not_contains: T1
  spatial_window_size: "(32, 32, 32)"
  interp_order: 0
SYSTEM:
  cuda_devices: 
  num_threads: 4
  num_gpus: 1
  model_dir: "./models/model_holisticnet"
NETWORK:
  name: holisticnet
  activation_function: elu
  batch_size: 1
  decay: 0.1
  reg_type: L2
  volume_padding_size: 21
  histogram_ref_file: "./example_volumes/multimodal_BRATS/standardisation_models.txt"
  norm_type: percentile
  cutoff: "(0.01, 0.99)"
  normalisation: true
  whitening: true
  normalise_foreground_only: true
  foreground_type: otsu_plus
  multimod_foreground_type: and
  queue_length: 512
  window_sampling: uniform
TRAINING:
  sample_per_volume: 5
  lr: 0.01
  loss_type: WGDL
  starting_iter: 0
  save_every_n: 5
  max_iter: 6
  max_checkpoints: 20
INFERENCE:
  border: "(5, 5, 5)"
  save_seg_dir: "./output/holisticnet"
  output_interp_order: 0
  output_prob: false
  spatial_window_size: "(64, 64, 64)"
SEGMENTATION:
  image: T1,T2,T1c,Flair
  label: label
  output_prob: false
  num_classes: 5
  label_normalisation: true
