---
IXI image:
  path_to_search: "./example_volumes/autoencoder_test_data"
  filename_contains: T1
  filename_not_contains: 
  spatial_window_size: "(24, 24, 24)"
Encoded features:
  path_to_search: "./output/vae_demo_features"
  spatial_window_size: "(1, 1, 1)"
SYSTEM:
  cuda_devices: 
  num_threads: 2
  num_gpus: 1
  queue_length: 20
  model_dir: "./models/model_autoencoder_demo"
NETWORK:
  name: vae
  decay: 1.0e-07
  reg_type: L2
  batch_size: 50
  normalisation: false
  whitening: false
TRAINING:
  sample_per_volume: 1
  lr: 0.0001
  loss_type: VariationalLowerBound
  starting_iter: 0
  save_every_n: 100
  tensorboard_every_n: 2
  max_iter: 10000
  max_checkpoints: 20
INFERENCE:
  save_seg_dir: "./output/vae_demo_sample"
  spatial_window_size: "(24, 24, 24)"
AUTOENCODER:
  image: IXI image
  feature: Encoded features
  inference_type: sample
  noise_stddev: 1
  n_interpolations: 10
