---
T1:
  path_to_search: "./example_volumes/monomodal_parcellation"
  filename_contains: T1
  filename_not_contains: 
  spatial_window_size: "(32, 32, 32)"
  pixdim: "(1.0, 1.0, 1.0)"
  axcodes: "(A, R, S)"
  interp_order: 3
parcellation:
  path_to_search: "./example_volumes/monomodal_parcellation"
  filename_contains: Label
  filename_not_contains: 
  spatial_window_size: "(32, 32, 32)"
  pixdim: "(1.0, 1.0, 1.0)"
  axcodes: "(A, R, S)"
  interp_order: 0
SYSTEM:
  cuda_devices: 
  num_threads: 2
  num_gpus: 1
  model_dir: "./models/model_vnet"
NETWORK:
  name: vnet
  activation_function: prelu
  batch_size: 1
  decay: 0
  reg_type: L2
  volume_padding_size: 21
  histogram_ref_file: "./example_volumes/monomodal_parcellation/standardisation_models.txt"
  norm_type: percentile
  cutoff: "(0.01, 0.99)"
  normalisation: true
  whitening: true
  normalise_foreground_only: true
  foreground_type: otsu_plus
  multimod_foreground_type: and
  queue_length: 1
  window_sampling: uniform
TRAINING:
  sample_per_volume: 32
  rotation_angle: "(-10.0, 10.0)"
  scaling_percentage: "(-10.0, 10.0)"
  lr: 0.0001
  loss_type: Dice
  starting_iter: 0
  save_every_n: 5
  max_iter: 6
  max_checkpoints: 20
INFERENCE:
  border: "(5, 5, 5)"
  save_seg_dir: "./output/vnet"
  output_interp_order: 0
  spatial_window_size: "(0, 0, 3)"
SEGMENTATION:
  image: T1
  label: parcellation
  output_prob: false
  num_classes: 160
  label_normalisation: true
